// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avujpdvxxcdibswwhdxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2dWpwZHZ4eGNkaWJzd3doZHhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTA1MTIsImV4cCI6MjA2ODU4NjUxMn0.ofME3s3_ggbNC4PSs5bRiRe4dLlOnS_Jqg5EOSq9zo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});